DROP TABLE IF EXISTS bill_items;
DROP TABLE IF EXISTS bills;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS shop_users;
DROP TABLE IF EXISTS shops;
DROP TABLE IF EXISTS users;
