name = "retailflow-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "retailflow-d1"
database_id = "27838c6a-2b30-487a-a42f-fa5545e69b72"
