import 'package:flutter/foundation.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:intl/intl.dart';

class LedgerPdfService {
  static Future<Uint8List> generateLedgerPdf({
    required String title,
    required String partyName,
    required String phone,
    required double totalOutstanding,
    required List<Map<String, dynamic>> transactions,
  }) async {
    final pdf = pw.Document();
    final fmt = NumberFormat('#,##,##0.00');
    final dateFmt = DateFormat('dd MMM yyyy, hh:mm a');

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return [
            // Header Section
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold, color: PdfColors.blue900)),
                    pw.SizedBox(height: 4),
                    pw.Text('Name: $partyName', style: pw.TextStyle(fontSize: 14)),
                    if (phone.isNotEmpty) pw.Text('Phone: $phone', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                  ],
                ),
                pw.Container(
                  padding: const pw.EdgeInsets.all(12),
                  decoration: pw.BoxDecoration(
                    color: PdfColors.grey100,
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                    border: pw.Border.all(color: PdfColors.grey300),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Total Outstanding', style: pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
                      pw.Text('Rs. ${fmt.format(totalOutstanding)}', style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.red800)),
                      pw.SizedBox(height: 4),
                      pw.Text('Date: ${dateFmt.format(DateTime.now())}', style: const pw.TextStyle(fontSize: 10)),
                    ],
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 24),
            pw.Divider(color: PdfColors.grey300),
            pw.SizedBox(height: 16),
            pw.Text('Transaction History', style: pw.TextStyle(fontSize: 16, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 12),

            // Transactions Table
            if (transactions.isEmpty)
              pw.Center(child: pw.Text('No transactions found.', style: pw.TextStyle(color: PdfColors.grey)))
            else
              pw.TableHelper.fromTextArray(
                context: context,
                border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
                headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white, fontSize: 11),
                headerDecoration: const pw.BoxDecoration(color: PdfColors.blue800),
                cellStyle: const pw.TextStyle(fontSize: 10),
                cellPadding: const pw.EdgeInsets.all(8),
                headers: ['Date', 'Description', 'Amount'],
                data: transactions.map((t) {
                  final amount = (t['amount'] as num?)?.toDouble() ?? 0.0;
                  final amtText = 'Rs. ${fmt.format(amount)}';
                  
                  return [
                    t['date'] ?? '',
                    t['description'] ?? '',
                    amtText,
                  ];
                }).toList(),
              ),

            pw.SizedBox(height: 30),
            pw.Center(
              child: pw.Text(
                'Generated by App',
                style: pw.TextStyle(fontSize: 10, color: PdfColors.grey600, fontStyle: pw.FontStyle.italic),
              ),
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }
}
