import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'home': 'Home',
      'inventory': 'Inventory',
      'customers': 'Customers',
      'reports': 'Reports',
      'settings': 'Settings',
      'shop_settings': 'Shop Settings',
      'security': 'Security',
      'preferences': 'Preferences',
      'printer_settings': 'Printer Settings',
      'language': 'Language',
      'dark_mode': 'Dark Mode',
      'notifications': 'Notifications',
      'pin_lock': 'PIN Lock',
      'fingerprint': 'Fingerprint',
      'sign_out': 'Sign Out',
      'about_app': 'About App',
      'shop_name': 'Shop Name',
      'shop_address': 'Shop Address',
      'gstin': 'GSTIN',
      'currency': 'Currency',
      'good_morning': 'Good Morning ☀️',
      'good_afternoon': 'Good Afternoon 🌤️',
      'good_evening': 'Good Evening 🌙',
      'new_bill': 'New Bill',
      'add_customer': 'Add Customer',
      'total_products': 'Total Products',
      'today_sales': 'Today\'s Sales',
      'monthly_sales': 'Monthly Sales',
      'low_stock': 'Low Stock',
      'quick_actions': 'Quick Actions',
      'recent_sales': 'Recent Sales',
      'top_categories': 'Top Categories',
      'view_all': 'View All',
      'search': 'Search',
      'products': 'Products',
      'add_product': 'Add Product',
      'search_products': 'Search Products...',
      'search_customers': 'Search Customers...',
      'all_categories': 'All Categories',
      'price': 'Price',
      'stock': 'Stock',
      'total_spent': 'Total Spent',
      'total_orders': 'Total Orders',
      'call': 'Call',
      'create_invoice': 'Create Invoice',
      'select_customer': 'Select Customer',
      'add_items': 'Add Items',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'grand_total': 'Grand Total',
      'print_share': 'Print Invoice',
      'sales_reports': 'Sales Reports',
      'revenue': 'Revenue',
      'payment_methods': 'Payment Methods',
      'fingerprint_title': 'Fingerprint Lock',
      'fingerprint_desc': 'Enable biometric fingerprint authentication for fast and secure access.',
      'fingerprint_enabled': 'Fingerprint Lock Enabled!',
      'fingerprint_disabled': 'Fingerprint Lock Disabled',
      'close': 'Close',
      'toggle_option': 'Fingerprint Lock Switch',
    },
    'mr': {
      'home': 'मुख्यपृष्ठ',
      'inventory': 'इन्व्हेंटरी',
      'customers': 'ग्राहक',
      'reports': 'रिपोर्ट्स',
      'settings': 'सेटिंग्ज',
      'shop_settings': 'दुकान सेटिंग्ज',
      'security': 'सुरक्षा',
      'preferences': 'प्राधान्ये',
      'printer_settings': 'प्रिंटर सेटिंग्ज',
      'language': 'भाषा (Language)',
      'dark_mode': 'डार्क मोड',
      'notifications': 'सूचना (Notifications)',
      'pin_lock': 'पिन लॉक',
      'fingerprint': 'फिंगरप्रिंट सुरक्षा',
      'sign_out': 'साइन आउट',
      'about_app': 'अॅप बद्दल',
      'shop_name': 'दुकानाचे नाव',
      'shop_address': 'दुकानाचा पत्ता',
      'gstin': 'जीएसटी (GSTIN)',
      'currency': 'चलन',
      'good_morning': 'शुभ सकाळ ☀️',
      'good_afternoon': 'शुभ दुपार 🌤️',
      'good_evening': 'शुभ संध्याकाळ 🌙',
      'new_bill': 'नवीन बिल',
      'add_customer': 'ग्राहक जोडा',
      'total_products': 'एकूण उत्पादने',
      'today_sales': 'आजची विक्री',
      'monthly_sales': 'महिन्याची विक्री',
      'low_stock': 'कमी साठा',
      'quick_actions': 'जलद कृती',
      'recent_sales': 'अलीकडील विक्री',
      'top_categories': 'प्रमुख श्रेणी',
      'view_all': 'सर्व पहा',
      'search': 'शोधा',
      'products': 'उत्पादने',
      'add_product': 'नवीन उत्पादन',
      'search_products': 'उत्पादने शोधा...',
      'search_customers': 'ग्राहक शोधा...',
      'all_categories': 'सर्व श्रेणी',
      'price': 'किंमत',
      'stock': 'साठा',
      'total_spent': 'एकूण खर्च',
      'total_orders': 'एकूण ऑर्डर्स',
      'call': 'कॉल',
      'create_invoice': 'बिल तयार करा',
      'select_customer': 'ग्राहक निवडा',
      'add_items': 'वस्तू जोडा',
      'subtotal': 'उपएकूण',
      'discount': 'सवलत',
      'grand_total': 'एकूण बिल',
      'print_share': 'प्रिंट बिल',
      'sales_reports': 'विक्री रिपोर्ट्स',
      'revenue': 'महसूल',
      'payment_methods': 'पेमेंट पद्धती',
      'fingerprint_title': 'फिंगरप्रिंट सुरक्षा',
      'fingerprint_desc': 'जलद आणि सुरक्षित प्रवेशासाठी फिंगरप्रिंट बायोमेट्रिक लॉक चालू करा.',
      'fingerprint_enabled': 'फिंगरप्रिंट लॉक चालू केले!',
      'fingerprint_disabled': 'फिंगरप्रिंट लॉक बंद केले',
      'close': 'बंद करा',
      'toggle_option': 'फिंगरप्रिंट लॉक चालू / बंद करा',
    },
    'hi': {
      'home': 'होम',
      'inventory': 'इन्वेंटरी',
      'customers': 'ग्राहक',
      'reports': 'रिपोर्ट्स',
      'settings': 'सेटिंग्स',
      'shop_settings': 'दुकान की सेटिंग्स',
      'security': 'सुरक्षा',
      'preferences': 'प्राथमिकताएं',
      'printer_settings': 'प्रिंटर सेटिंग्स',
      'language': 'भाषा (Language)',
      'dark_mode': 'डार्क मोड',
      'notifications': 'सूचनाएं',
      'pin_lock': 'पिन लॉक',
      'fingerprint': 'फिंगरप्रिंट सुरक्षा',
      'sign_out': 'साइन आउट',
      'about_app': 'ऐप के बारे में',
      'shop_name': 'दुकान का नाम',
      'shop_address': 'दुकान का पता',
      'gstin': 'जीएसटी (GSTIN)',
      'currency': 'मुद्रा',
      'good_morning': 'सुप्रभात ☀️',
      'good_afternoon': 'शुभ दोपहर 🌤️',
      'good_evening': 'शुभ संध्या 🌙',
      'new_bill': 'नया बिल',
      'add_customer': 'ग्राहक जोड़ें',
      'total_products': 'कुल उत्पाद',
      'today_sales': 'आज की बिक्री',
      'monthly_sales': 'महीने की बिक्री',
      'low_stock': 'कम स्टॉक',
      'quick_actions': 'त्वरित कार्य',
      'recent_sales': 'हाल की बिक्री',
      'top_categories': 'शीर्ष श्रेणियां',
      'view_all': 'सभी देखें',
      'search': 'खोजें',
      'products': 'उत्पाद',
      'add_product': 'उत्पाद जोड़ें',
      'search_products': 'उत्पाद खोजें...',
      'search_customers': 'ग्राहक खोजें...',
      'all_categories': 'सभी श्रेणियां',
      'price': 'कीमत',
      'stock': 'स्टॉक',
      'total_spent': 'कुल खर्च',
      'total_orders': 'कुल ऑर्डर',
      'call': 'कॉल',
      'create_invoice': 'बिल बनाएं',
      'select_customer': 'ग्राहक चुनें',
      'add_items': 'वस्तुएं जोड़ें',
      'subtotal': 'उप-योग',
      'discount': 'छूट',
      'grand_total': 'कुल योग',
      'print_share': 'प्रिंट बिल',
      'sales_reports': 'बिक्री रिपोर्ट',
      'revenue': 'राजस्व',
      'payment_methods': 'भुगतान के तरीके',
      'fingerprint_title': 'फिंगरप्रिंट सुरक्षा',
      'fingerprint_desc': 'तेज़ और सुरक्षित पहुँच के लिए फिंगरप्रिंट लॉक चालू करें।',
      'fingerprint_enabled': 'फिंगरप्रिंट लॉक चालू किया गया!',
      'fingerprint_disabled': 'फिंगरप्रिंट लॉक बंद किया गया',
      'close': 'बंद करें',
      'toggle_option': 'फिंगरप्रिंट लॉक चालू / बंद करें',
    }
  };

  String translate(String key) {
    return _localizedValues['en']?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'mr', 'hi'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
